---
title: "Coffee_visuzlizations"
author: "Hanna Matera"
date: "02/06/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

---
title: "CoffeeDataAnalysis- visualisations"
author: "Hania Matera"
date: "01 June 2021"
output: html_document
editor_options: 
  chunk_output_type: console
---


## Importing neccessary packages
```{r}
library(pacman)
p_load(tidyverse, sf, ggspatial, rnaturalearth, rnaturalearthdata)
p_load(leaflet, worldgeojson, highcharter, htmlwidgets)

```

# Loading the data 
```{r}
#read the data
data <- read_csv("arabica_data_cleaned.csv")
```

## Data cleaning
```{r}
# remove farms without coordinates 
data <- data %>% drop_na(location_coordinates)


# Create longitude and latitude columns
coordinates <- data.frame(do.call("rbind", strsplit(as.character(data$location_coordinates), ",", fixed = TRUE)))

coordinates <- coordinates %>% 
  rename(
    Y = X1,#latitude
    X = X2#longitude
    ) %>% 
  mutate(
    X = as.numeric(as.character(X)),
    Y = as.numeric(as.character(Y))
  )

data <- cbind(data, coordinates)

# Make geometry point column - shapefile
data <- st_as_sf(data, coords = c("X", "Y"), remove = FALSE, 
    crs = 4326, agr = "constant")


st_crs(data)

# Only keep relevant columns
data <- data[c("X1","X", "Y", "Region","Country.of.Origin","Farm.Name", "Processing.Method", "unit_of_measurement", "altitude_low_meters", "altitude_high_meters", "altitude_mean_meters", "Aroma", "Flavor", "Aftertaste", "Acidity", "Body", "Balance", "Uniformity", "Sweetness")]
```

# Mapping the location of coffee growing farms 
```{r}
#creating a map with leaflet that displays the coffee farms + layers to manipulate
basemap <- leaflet() %>%
  # add different provider tiles
  addProviderTiles("OpenStreetMap",group = "OpenStreetMap") %>%
  addProviderTiles("Stamen.Toner",group = "Stamen.Toner" ) %>%
  addProviderTiles("Stamen.Terrain", group = "Stamen.Terrain") %>%
  addProviderTiles("Esri.WorldStreetMap", group = "Esri.WorldStreetMap") %>%
  addProviderTiles("Wikimedia",group = "Wikimedia" ) %>%
  addProviderTiles("CartoDB.Positron",group = "CartoDB.Positron") %>%
  addProviderTiles("Esri.WorldImagery",group = "Esri.WorldImagery") %>%
# add a layers control
  addLayersControl(baseGroups = c(
      "OpenStreetMap", "Stamen.Toner",
      "Stamen.Terrain", "Esri.WorldStreetMap",
      "Wikimedia", "CartoDB.Positron", "Esri.WorldImagery"),
    # position it on the topleft
    position = "topleft")

#adding the pins 
icon.fa <- makeAwesomeIcon(
  icon = "coffee", markerColor = "green",
  library = "fa",
  iconColor = "black"
)

#merging the map and icons
map_1 <- basemap %>%
  addAwesomeMarkers(
    lat = data$Y,
    lng =data$X,
    label = data$Region,
    icon = icon.fa
  )

#display
map_1



```

#Building interactive maps -for aroma, acidity and balance
```{r}

#necessary preprocessing 
#renaming country names so that they match the shapes of the countries - for plotting 
data$Country.of.Origin[data$Country.of.Origin == "United States (Hawaii)"] <- "United States of America"
data$Country.of.Origin[data$Country.of.Origin == "United States (Puerto Rico)"] <- "United States of America"
data$Country.of.Origin[data$Country.of.Origin == "United States"] <- "Colombia" # there has been a mistake and all beans marked as coming from the USA were in fact from Columbia 
data$Country.of.Origin[data$Country.of.Origin == "Tanzania, United Republic Of"] <- "Tanzania"


#aggregating scores by countries + rounding to 2 decimal places 
# mean aroma by country+  renaming columns
mean_aroma_by_country <- aggregate(data$Aroma,by=list(data$Country.of.Origin), mean) 
colnames(mean_aroma_by_country)[1] <- "country"
mean_aroma_by_country$x <- round(mean_aroma_by_country$x,2)

# mean acidity by country+  renaming columns +rounding to 2 decimal places 
mean_acidity_by_country <- (aggregate(data$Acidity,by=list(data$Country.of.Origin), mean)
colnames(mean_acidity_by_country)[1] <- "country"
mean_acidity_by_country$x <- round(mean_acidity_by_country$x,2)


# mean balance by country+  renaming columns +rounding to 2 decimal places 
mean_balance_by_country <- aggregate(data$Balance,by=list(data$Country.of.Origin), mean) 
colnames(mean_balance_by_country)[1] <- "country"
mean_balance_by_country$x <- round(mean_balance_by_country$x,2)

#building interactive maps 
#Aroma
aroma_map <- highchart() %>%
  hc_add_series_map(
    worldgeojson,mean_aroma_by_country, value = "x", joinBy =c("name",'country'),
    name = "Mean score"
    )  %>% 
  hc_colorAxis( min = 370, max = 840,minColor="#F1B6DA",maxColor="#CA0020") %>% 
  hc_title(text = "World Map") %>% 
  hc_subtitle(text = "Coffee Aroma")

  
aroma_map


#Acidity
acidity_map <- highchart() %>%
  hc_add_series_map(
    worldgeojson,mean_acidity_by_country, value = "x", joinBy =c("name",'country'),
    name = "Mean score"
    )  %>% 
  hc_colorAxis( min = 400, max = 840,minColor="#B8E186",maxColor="#018571") %>% 
  hc_title(text = "World Map") %>% 
  hc_subtitle(text = "Coffee Acidity")

  
acidity_map



#Balance
balance_map <- highchart() %>%
  hc_add_series_map(
    worldgeojson,mean_balance_by_country, value = "x", joinBy =c("name",'country'),
    name = "Mean score"
    )  %>% 
  hc_colorAxis( min = 60, max = 825,minColor="#EFFF7F",maxColor="#E66101") %>% 
  hc_title(text = "World Map") %>% 
  hc_subtitle(text = "Coffee Balance")

  
balance_map

```

## mapping with leaflet- DOESNT FUCKING WORK ;(
```{r}
#means for every flavor characteristics by country 
d <- data %>% group_by(Country.of.Origin) %>% 
  summarise_at(.vars = names(.)[12:19],
               .funs = c(mean="mean"))


#renaming
colnames(d)[1] <- "NAME"
#preparing the data 
# Downloading the shapefile. (note that I store it in a folder called DATA. You have to change that if needed.)
download.file("http://thematicmapping.org/downloads/TM_WORLD_BORDERS_SIMPL-0.3.zip" , destfile="DATA/world_shape_file.zip")
# You now have it in your current working directory, have a look!

# Unzip this file. You can do it with R (as below), or clicking on the object you downloaded.
system("unzip DATA/world_shape_file.zip")
#  -- > You now have 4 files. One of these files is a .shp file! (TM_WORLD_BORDERS_SIMPL-0.3.shp)

library(rgdal)
world_spdf <- readOGR( dsn= paste0(getwd()), layer="TM_WORLD_BORDERS_SIMPL-0.3",verbose=FALSE)

# 
world_spdf@data <- merge(world_spdf@data, d,by=c("NAME"))

# Create a color palette with handmade bins.
library(RColorBrewer)
mybins <- c(0,10,20,50,100,500,Inf)
mypalette <- colorBin( palette="YlOrBr", domain=world_spdf@data$NAME, na.color="transparent", bins=mybins)
 
# Prepare the text for tooltips:
mytext <- paste(
    "Country: ", world_spdf@data$NAME,"<br/>", 
    "Aroma: ", world_spdf@data$Aroma_mean, "<br/>", 
    "Flavor: ", round(world_spdf@data$Flavor_mean, 2), 
    sep="") %>%
  lapply(htmltools::HTML)



# Final Map
leaflet(world_spdf) %>% 
  addTiles()  %>% 
  #setView( lat=10, lng=0 , zoom=2) %>%
  addPolygons(
    fillColor = ~mypalette(Aroma_mean), 
    stroke=TRUE, 
    fillOpacity = 0.9, 
    color="white", 
    weight=0.3,
    label = mytext,
    labelOptions = labelOptions( 
      style = list("font-weight" = "normal", padding = "3px 8px"), 
      textsize = "13px", 
      direction = "auto"
    )
  ) %>%
  addLegend( pal=mypalette, values=~Aroma_mean, opacity=0.9, title = "mean aroma", position = "bottomleft" )

class(data)


d$NAME <- as.factor(d$NAME)
levels(d$NAME)


```




